### ISSUE TITLE
improve client/server to restart on unfinished files (depends on [issue 2])

### ISSUE THREAD

**Issue by mikp** [mikp/cmb-mobile-offloading#4]
[issue 2](https://github.com/mikp/cmb-mobile-offloading/issues/2)

**Comment by mikp** [comment]
[issue 2](https://github.com/mikp/cmb-mobile-offloading/issues/2)

**Comment by JimmyAbuAlDenien** [comment]
Implemented this task by caching the total number of bytes successfully transferred to client and then updated the client / server to communicate to read and write the file from where it stopped in case of error.

**Comment by mikp** [comment]
This was throwing exceptions sometimes due to threading /which we do not need). fixed this: c8c4a67610668f900c210683043a1a7834fee84f
